# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce6a364761aa8f34f1b3068e4b570bc847a15b87bfb9a000b6a6b188ed921409362ade904cf2271ffaadf1ee1aac6df50fce0fbe43798049c2e099b706bc22b4

test:
  secret_key_base: 895efc94598a0833be70e1a4bbd616833d8103a745acb6238adba3b18223919f58aa92a061dd10e903f0ac434c4bdbe54d0f6a1bfce02c8db7a28d8ec41df365

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
